FROM triaxis/simplicity-studio:4-gcc-7

RUN apt-get update && apt-get install -y \
    libqt5widgets5 \
    && rm -rf /var/lib/apt/lists/*

RUN /opt/SimplicityStudio_v4/studio \
    -application org.eclipse.equinox.p2.director \
    -r ${SILABS_REPOSITORY} \
    -i com.silabs.apack.commander.feature.feature.group \
    -i com.silabs.sdk.gecko_platform.v2.7.feature.feature.group/2.7.3.202003222009-256 \
    && rm -rf /opt/SimplicityStudio_v4/p2/org.eclipse.equinox.p2.core/cache

ENV EFM32_SDK_ORIGIN="/opt/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.7/"
ENV SI_COMMANDER="/opt/SimplicityStudio_v4/developer/adapter_packs/commander/commander"
ENV PATH="/opt/SimplicityStudio_v4/developer/adapter_packs/commander:${PATH}"
